# Basic Information 
url: "/qlt315.github.io "
title: Langtian Qin
position: PhD Student in Computer Science (CS)
affiliation: University of California, Irvine
affiliation_link: https://ics.uci.edu/
email: qlt315@126.com / langtiq@uci.edu

# Search Engine Optimization (SEO)
keywords: langtian qin, qin langtian, langtianqin, qinlangtian
canonical: https://qlt315.github.io/
description: CS phd student at UC Irvine

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=2gaiM-wAAAAJ
cv_link: ./assets/CV_LangtianQin.pdf
github_link: https://github.com/qlt315/
linkedin: https://www.linkedin.com/in/qlt315/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/qlt.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: Eh8e0SxTYwqs1ecwT0Emys86OXzFkNMRWNwYSHN2SPw

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
